#!/bin/sh 

# variable
LOGIN_NAME=""
VIEW_PATH="printer"

# functions
function cecho { echo -e "\e[34m$*\e[m"; }


cecho "Install start"

# Get Login Name
cecho "### First, enter your login name ###"
cecho "ex) t14000tk"
read LOGIN_NAME

ls /home/${LOGIN_NAME}/CNSiMac

# Generate files from Login Name
cecho "### Make files from your login name in 'lib' folder ###"

cp `pwd`/view/js/ajax.js                      `pwd`/lib/view/js/
cp `pwd`/view/js/jquery-migrate-1.2.1.min.js  `pwd`/lib/view/js/
cp `pwd`/view/js/jquery-1.11.0.min.js         `pwd`/lib/view/js/

sed s/#{your_login_name}/${LOGIN_NAME}/g \
  `pwd`/view/js/script.js >> `pwd`/lib/view/js/script.js
sed s/#{your_login_name}/${LOGIN_NAME}/g \
  `pwd`/cron/make_json.py >> `pwd`/lib/cron/make_json.py
sed s/#{your_login_name}/${LOGIN_NAME}/g \
  `pwd`/cron/move_mail.py >> `pwd`/lib/cron/move_mail.py
sed s/#{your_login_name}/${LOGIN_NAME}/g \
  `pwd`/static/json.php   >> `pwd`/lib/static/json.php

# Make files for crontab
cecho "### Make 'src' folder under your home directory### "

if [ ! -d /home/${LOGIN_NAME}/src ]; then
  mkdir /home/${LOGIN_NAME}/src
fi

cp `pwd`/lib/cron/make_json.py ~/src/
cp `pwd`/lib/cron/move_mail.py ~/src/

# Make public_html folder
if [ ! -d /home/${LOGIN_NAME}/public_html ]; then
  cecho "### Make 'public_html' folder under your home directory ###"
  mkdir /home/${LOGIN_NAME}/public_html
fi

# Make public folder for web application
cecho "### Make 'printer' folder under your 'public_html' folder ###"
if [ ! -d /home/${LOGIN_NAME}/public_html/${VIEW_PATH} ]; then
  mkdir /home/${LOGIN_NAME}/public_html/${VIEW_PATH}
else
  cecho "### The 'printer' folder is already exists ###"
  cecho "### Are you sure you want to delete files under 'printer' folder? ###"
  cecho "(yes/no)"

  while :
  do
    read CONFIRM

    case ${CONFIRM} in
      "yes")
        cecho "### Delete files and copy some files ###"
        rm -r ~/public_html/printer/*
        break
        ;;
      "no")
        cecho "### Then, enter folder name you like ###"
        cecho "ex) 'CNS_printer'"
        while :
        do
          read VIEW_PATH

          case VIEW_PATH in
            "")
              cecho "### Please enter folder name ###"
              ;;
            *)
              break
              ;;
          esac
        done
        break
        ;;
      *)
        cecho "### Plese enter 'yes' or 'no' ###"
        read CONFIRM
        ;;
    esac
  done
fi

# Copy files to public folder
cecho "### Is installoing... ###"

cp    `pwd`/view/index.html      ~/public_html/${VIEW_PATH}/
cp -R `pwd`/view/Flat-UI-master  ~/public_html/${VIEW_PATH}/
cp -R `pwd`/lib/view/js          ~/public_html/${VIEW_PATH}/
cp    `pwd`/lib/static/json.php  ~/public_html/${VIEW_PATH}/

cecho "### Installation is completed!! ###"
cecho "### You can access to the website ###"
cecho "### http://web.sfc.keio.ac.jp/~${LOGIN_NAME}/${VIEW_PATH}/index.html ###"
