#!/bin/zsh 

# variable
LOGIN_NAME=""
VIEW_PATH="printer"

# functions
function cecho { echo -e "\e[34m$*\e[m"; }

cecho "### Install start ###"

# Get Login Name
cecho "### First, enter your login name ###"
cecho "ex) t14000tk"
read LOGIN_NAME

# Make public_html folder
if [ ! -d /home/${LOGIN_NAME}/public_html ]; then
  cecho "### Make 'public_html' folder under your home directory ###"
  mkdir /home/${LOGIN_NAME}/public_html
fi

# Make public folder for web application
cecho "### Make 'printer' folder under your 'public_html' folder ###"
if [ ! -d /home/${LOGIN_NAME}/public_html/${VIEW_PATH} ]; then
  mkdir /home/${LOGIN_NAME}/public_html/${VIEW_PATH}
else
  cecho "### The 'printer' folder is already exists ###"
  cecho "### Are you sure you want to delete files under 'printer' folder? ###"
  cecho "(yes/no)"

  while :
  do
    read CONFIRM

    case ${CONFIRM} in
      "yes")
        cecho "### Delete files and copy some files ###"
        rm -r ~/public_html/printer/*
        break
        ;;
      "no")
        cecho "### Then, enter folder name you like ###"
        cecho "ex) 'CNS_printer'"
        while :
        do
          read VIEW_PATH

          case VIEW_PATH in
            "")
              cecho "### Please enter folder name ###"
              ;;
            *)
              cecho "### The folder name is ${VIEW_PATH} ###"
              break
              ;;
          esac
        done
        break
        ;;
      *)
        cecho "### Plese enter 'yes' or 'no' ###"
        read CONFIRM
        ;;
    esac
  done
fi

# Generate files from Login Name and View Path
cecho "### Make files from your login name in 'lib' folder ###"

cp `pwd`/view/js/ajax.js                      `pwd`/lib/view/js/
cp `pwd`/view/js/jquery-migrate-1.2.1.min.js  `pwd`/lib/view/js/
cp `pwd`/view/js/jquery-1.11.0.min.js         `pwd`/lib/view/js/

sed s/#{your_login_name}/${LOGIN_NAME}/g `pwd`/view/js/script.js | \
  sed s/#{printer}/${VIEW_PATH}/g > `pwd`/lib/view/js/script.js
sed s/#{your_login_name}/${LOGIN_NAME}/g `pwd`/cron/make_json    | \
  sed s/#{printer}/${VIEW_PATH}/g > `pwd`/lib/cron/make_json
sed s/#{your_login_name}/${LOGIN_NAME}/g `pwd`/static/json.php   | \
  sed s/#{printer}/${VIEW_PATH}/g > `pwd`/lib/static/json.php
sed s/#{your_login_name}/${LOGIN_NAME}/g \
  `pwd`/cron/find_mail    > `pwd`/lib/cron/find_mail

# Make files for crontab
cecho "### Make 'src' folder under your home directory### "

if [ ! -d /home/${LOGIN_NAME}/src ]; then
  mkdir /home/${LOGIN_NAME}/src
fi

cp `pwd`/lib/cron/make_json /home/${LOGIN_NAME}/src/
cp `pwd`/lib/cron/find_mail /home/${LOGIN_NAME}/src/

chmod 755 /home/${LOGIN_NAME}/src/make_json
chmod 755 /home/${LOGIN_NAME}/src/find_mail

# Copy files to public folder
cecho "### Is installoing... ###"

cp    `pwd`/view/index.html      ~/public_html/${VIEW_PATH}/
cp -R `pwd`/view/Flat-UI-master  ~/public_html/${VIEW_PATH}/
cp -R `pwd`/lib/view/js          ~/public_html/${VIEW_PATH}/
cp    `pwd`/lib/static/json.php  ~/public_html/${VIEW_PATH}/

cecho "### Installation is completed!! ###"
cecho "### You can access to the website ###"
cecho "### http://web.sfc.keio.ac.jp/~${LOGIN_NAME}/${VIEW_PATH}/index.html ###"
