#!/bin/sh

# Description:
#   Find CNS Printer Status mail and read file.
#   Then, write data to ~/src/mails.txt
# 
# Crontab:
#   */10 * * * * /home/#{your_login_name}/src/find_mail

# Replace with sed command
LOGIN_NAME=#{your_login_name}

MAIL_PATH_CUR=/home/${LOGIN_NAME}/Maildir/cur/*
MAIL_PATH_NEW=/home/${LOGIN_NAME}/Maildir/new/*
MAIL_FILE=/home/${LOGIN_NAME}/src/mails.txt
NEWEST_MAIL_DATE=0

# Scan mails
for file in ${MAIL_PATH_CUR} ${MAIL_PATH_NEW}
do
  if test "`grep 'Subject:\ CNS\ Printer\ Status' ${file}`" != ""; then
    FILE_DATE=`date +%Y%m%d%H -r ${file}`
    if test ${NEWEST_MAIL_DATE} -le ${FILE_DATE}; then
      tail -n 18 ${file} > ${MAIL_FILE}
      NEWEST_MAIL_DATE=${FILE_DATE}
    fi
  fi
done
