#!/bin/sh

# replace with sed command
LOGIN_NAME=#{your_login_name}

MAIL_PATH=/home/${LOGIN_NAME}/Maildir/cur/*
MAIL_FILE=/home/${LOGIN_NAME}/src/mails.txt

# Reset the mails.txt
echo "" > ${MAIL_FILE}

# Scan mails
for file in ${MAIL_PATH}
do
  if test "`grep 'CNS\ Printer\ Status' ${file}`" != ""; then
    FILE_DATE=`date +%Y%m%d%H -r ${file}`
    NOW_DATE=`date +%Y%m%d%H`
    if test `expr ${NOW_DATE} - ${FILE_DATE}` -le 10; then
      cat  ${file} >> ${MAIL_FILE}
      echo ""      >> ${MAIL_FILE}
    fi
  fi
done
